# Generated by Django 5.2 on 2025-04-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_categoria_alter_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('medicamento', 'Medicamento'), ('cosmetico', 'Cosmético'), ('suplemento', 'Suplemento'), ('higiene', 'Higiene Pessoal'), ('perfumaria', 'Perfumaria'), ('bem_estar', 'Bem-estar'), ('veterinario', 'Produtos Veterinários')], max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
