# Generated by Django 5.2 on 2025-05-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
    ]
