# Generated by Django 5.2 on 2025-05-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_em_estoque', models.IntegerField()),
                ('categoria', models.CharField(choices=[('medicamento', 'Medicamento'), ('cosmetico', 'Cosmético'), ('suplemento', 'Suplemento'), ('higiene', 'Higiene Pessoal'), ('perfumaria', 'Perfumaria'), ('bem_estar', 'Bem-estar'), ('veterinario', 'Produtos Veterinários')], max_length=100)),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_validade', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='estoque.produto')),
            ],
        ),
    ]
