# Generated by Django 5.2 on 2025-05-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_em_estoque',
        ),
    ]
