# Generated by Django 5.2 on 2025-05-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_quantidade_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
