# Generated by Django 5.2 on 2025-06-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
